name: Tinybird - CD Workflow

on:
   workflow_dispatch:
push:
   branches:
      - main
jobs:
   cd:  # deploy changes to workspace 'web analytics starter kit'
      uses: cd_template.yml
      with:
         data_project_dir: tinybird
      secrets:
         tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}  # set Workspace admin token in GitHub secrets
         tb_host: https://api.us-east.tinybird.co

